
```sql
-- =========================================================
-- PROJECT: Customer Shopping Behavior Analysis Using SQL-PYTHON-POWER BI
-- DATABASE: PostgreSQL
-- =========================================================

-- =========================================================
-- DATA PREVIEW
-- =========================================================

SELECT * FROM customer;

-- =========================================================
-- DATA CLEANING
-- =========================================================

-- Check total number of rows
SELECT COUNT(*) AS total_rows
FROM customer;

-- Check NULL values
SELECT *
FROM customer
WHERE customer_id IS NULL
   OR gender IS NULL
   OR age IS NULL
   OR item_purchased IS NULL
   OR category IS NULL
   OR purchase_amount_usd IS NULL
   OR shipping_type IS NULL
   OR review_rating IS NULL
   OR discount_applied IS NULL
   OR subscription_status IS NULL
   OR previous_purchases IS NULL;

-- =========================================================
-- DATA EXPLORATION
-- =========================================================

-- Total number of customers
SELECT COUNT(DISTINCT customer_id) AS total_customers
FROM customer;

-- Available product categories
SELECT DISTINCT category
FROM customer;

-- Available shipping types
SELECT DISTINCT shipping_type
FROM customer;

-- =========================================================
-- BUSINESS PROBLEMS & ANALYSIS
-- =========================================================

-- Q1. What is the total revenue generated by male vs. female customers?

SELECT
    gender,
    SUM(purchase_amount_usd) AS total_revenue
FROM customer
GROUP BY gender
ORDER BY total_revenue DESC;

-- =========================================================

-- Q2. Which customers used a discount but still spent more than
-- the average purchase amount?

SELECT
    customer_id,
    purchase_amount_usd
FROM customer
WHERE discount_applied = 'Yes'
  AND purchase_amount_usd >= (
      SELECT AVG(purchase_amount_usd)
      FROM customer
  );

-- =========================================================

-- Q3. Which are the top 5 products with the highest
-- average review rating?

SELECT
    item_purchased,
    ROUND(AVG(review_rating::NUMERIC), 2) AS average_product_rating
FROM customer
GROUP BY item_purchased
ORDER BY average_product_rating DESC
LIMIT 5;

-- =========================================================

-- Q4. Compare the average purchase amounts between
-- Standard and Express shipping.

SELECT
    shipping_type,
    ROUND(AVG(purchase_amount_usd), 2) AS average_purchase_amount
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

-- =========================================================

-- Q5. Do subscribed customers spend more?
-- Compare average spend and total revenue between
-- subscribers and non-subscribers.

SELECT
    subscription_status,
    COUNT(customer_id) AS total_customers,
    ROUND(AVG(purchase_amount_usd), 2) AS average_spend,
    ROUND(SUM(purchase_amount_usd), 2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue DESC;

-- =========================================================

-- Q6. Which 5 products have the highest percentage
-- of purchases with discounts applied?

SELECT
    item_purchased,
    ROUND(
        100.0 * SUM(
            CASE
                WHEN discount_applied = 'Yes' THEN 1
                ELSE 0
            END
        ) / COUNT(*),
        2
    ) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- =========================================================

-- Q7. Segment customers into New, Returning,
-- and Loyal based on previous purchases.

WITH customer_type AS (
    SELECT
        customer_id,
        previous_purchases,
        CASE
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer
)

SELECT
    customer_segment,
    COUNT(*) AS number_of_customers
FROM customer_type
GROUP BY customer_segment
ORDER BY number_of_customers DESC;

-- =========================================================

-- Q8. What are the top 3 most purchased products
-- within each category?

WITH item_counts AS (
    SELECT
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)

SELECT
    item_rank,
    category,
    item_purchased,
    total_orders
FROM item_counts
WHERE item_rank <= 3;

-- =========================================================

-- Q9. Are repeat buyers (more than 5 previous purchases)
-- also likely to subscribe?

SELECT
    subscription_status,
    COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- =========================================================

-- Q10. What is the revenue contribution of each age group?

SELECT
    age,
    SUM(purchase_amount_usd) AS total_revenue
FROM customer
GROUP BY age
ORDER BY total_revenue DESC;

-- =========================================================
-- END OF PROJECT
-- =========================================================
```
